---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: client
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: LoadBalancer
