---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: client
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
  type: LoadBalancer
