---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: rabbitmq-pvc-rabbitmq-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc
  local:
    path: /Users/Shared/containerStorage/rabbitmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - docker-desktop
