---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: client
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: LoadBalancer
