---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: html
    port: 9200
    targetPort: 9200
  - protocol: TCP
    name: transport
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
  type: LoadBalancer
