---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: client
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
