---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    name: client
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  type: LoadBalancer
